// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATxpmt0L5wBfKQEDldDdpNOIrWfjj_m4A',
    appId: '1:452905851509:web:aaa828a76107e3a416b63c',
    messagingSenderId: '452905851509',
    projectId: 'throunburger',
    authDomain: 'throunburger.firebaseapp.com',
    storageBucket: 'throunburger.firebasestorage.app',
    measurementId: 'G-H2HL5VTG5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74jr5EsjFs3h4mu965tm0LEnDbwEIQLU',
    appId: '1:452905851509:android:394461c488cfed4016b63c',
    messagingSenderId: '452905851509',
    projectId: 'throunburger',
    storageBucket: 'throunburger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQOLZDmROeEA6GRPy0DoACIDfnyTZI6_o',
    appId: '1:452905851509:ios:5ff44cfb097f82a616b63c',
    messagingSenderId: '452905851509',
    projectId: 'throunburger',
    storageBucket: 'throunburger.firebasestorage.app',
    iosBundleId: 'com.thronburger.thronburgerApp',
  );

}